#!/bin/bash

BASEPATH="${0%/*}"
BUILDXML="${BASEPATH}/build.xml"
XMLLINT="/usr/bin/xmllint"
ECHO="echo"
ANT="/usr/bin/ant"

INPUT="${1}"

tcnt="$(${XMLLINT} --xpath 'count(//target[not(starts-with(@name,"inactive_"))]/@name)' ${BUILDXML})"

print_build_target() {
  for((i=1;i<=${tcnt};i=$((i+1)))); do
    pel="$(${XMLLINT} --xpath 'string(//target[not(starts-with(@name,"inactive_"))]['"${i}"']/@name)' ${BUILDXML})"
    ${ECHO} "[${i}] ${pel}"
  done
}

t=""
while [ "${t}" = "" ]; do
  ${ECHO} "Bitte wählen Sie ein Ziel."
  print_build_target

  # use input passed if it is
  if [[ "${INPUT}" =~ ^[1-9]+[0-9]*$ ]] \
     && [ "${INPUT}" -gt "0" \
          -a "${INPUT}" -le "${tcnt}" ]; then 
    t="${INPUT}"
    ${ECHO} ${t}
  else
    read t
  fi
  
  if [ "${t}" = "" ]; then
    t=""
    break
  elif ! [[ "${t}" =~ ^[1-9]+[0-9]*$ ]] \
     || ! [ "${t}" -ge "1" -a "${t}" -le "${tcnt}" ]; then
       ${ECHO} "Ungültige Eingabe: ${t}."
       ${ECHO}
    t=""
  fi
done
${ECHO}

ts=""
if ! [ "${t}" = "" ]; then
  ts="$(${XMLLINT} --xpath 'string(//target[not(starts-with(@name,"inactive_"))]['"${t}"']/@name)' ${BUILDXML})"
fi
${ANT} -lib /usr/share/java/ant-contrib.jar -buildfile ${BUILDXML} \
                                            -silent ${ts}
